"""Low-latency Gemini prospect Meeting with strict turn serialization."""
from fastapi import Request
from fastapi.responses import HTMLResponse
import app as core

@core.app.get('/m4-smooth',response_class=HTMLResponse)
def m4_smooth(request:Request):
    user,redirect=core.login_required_redirect(request)
    if redirect:return redirect
    return HTMLResponse(r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>The Meeting</title><style>html,body{margin:0;height:100%;background:#f3f3ef;color:#1b1d19;font-family:system-ui,sans-serif}.wrap{height:100%;display:grid;place-items:center}.box{text-align:center;width:min(92vw,560px)}h1{font:500 28px Georgia,serif}.state{font:12px ui-monospace,monospace;color:#74786f;min-height:42px}.go{font:500 20px Georgia,serif;border:1px solid #c8cbc2;border-radius:999px;background:transparent;padding:14px 24px}.dot{width:10px;height:10px;border-radius:50%;background:#687a1c;margin:18px auto}</style></head><body><div class="wrap"><div class="box"><div class="dot"></div><h1>The Meeting</h1><button class="go" id="go">Enter</button><div id="state" class="state">ready</div></div></div><script>
const go=document.getElementById('go'),state=document.getElementById('state'),KEY='m4ProspectSession';let sessionId=sessionStorage.getItem(KEY)||((crypto.randomUUID&&crypto.randomUUID())||String(Date.now()));sessionStorage.setItem(KEY,sessionId);
let ws,ctx,stream,source,processor,started=false,userSpeaking=false,lastVoiceAt=0,voiceStartedAt=0,inputTranscript='',outputTranscript='',lastUserEndAt=0,firstModelAudioAt=0;
let phase='idle',generation=0,responseGeneration=0,pcmQueue=[],queuedSamples=0,playbackStarted=false,nextPlayTime=0,activeSources=new Set(),serverTurnComplete=false;
const RATE=24000,START=Math.round(RATE*.24),MIN=.09,TARGET=.16,END_SILENCE=1450,set=s=>state.textContent=s;
function b64(a){let s='',u=new Uint8Array(a);for(let i=0;i<u.length;i+=8192)s+=String.fromCharCode(...u.subarray(i,i+8192));return btoa(s)}function unb64(s){let x=atob(s),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u}function send(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}function merge(a,b){b=(b||'').trim();if(!b)return a;if(!a)return b;if(b.startsWith(a))return b;if(a.endsWith(b))return a;return(a+' '+b).trim()}
async function save(speaker,text,latency_ms=null){text=(text||'').trim();if(!text)return;try{await fetch('/api/m4/prospect-turn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId,speaker,text,latency_ms}),cache:'no-store'})}catch(e){}}
function flushResponse(){let a=inputTranscript.trim(),b=outputTranscript.trim(),l=(firstModelAudioAt&&lastUserEndAt)?Math.max(0,Math.round(firstModelAudioAt-lastUserEndAt)):null;inputTranscript='';outputTranscript='';firstModelAudioAt=0;if(a)save('prospect',a);if(b)save('m4',b,l)}
function down(i,ir,or=16000){if(ir===or)return i;let r=ir/or,n=Math.round(i.length/r),o=new Float32Array(n);for(let x=0;x<n;x++){let a=Math.floor(x*r),b=Math.min(Math.floor((x+1)*r),i.length),s=0;for(let j=a;j<b;j++)s+=i[j];o[x]=s/Math.max(1,b-a)}return o}function pcm16(f){let b=new ArrayBuffer(f.length*2),v=new DataView(b);for(let i=0;i<f.length;i++){let x=Math.max(-1,Math.min(1,f[i]));v.setInt16(i*2,x<0?x*32768:x*32767,true)}return b}
function resetAudio(){generation++;for(const s of activeSources){try{s.stop()}catch(_){}}activeSources.clear();pcmQueue=[];queuedSamples=0;playbackStarted=false;nextPlayTime=0;serverTurnComplete=false;responseGeneration=generation}
function finishIfDrained(g){if(g!==responseGeneration)return;if(serverTurnComplete&&!activeSources.size&&!pcmQueue.length){playbackStarted=false;nextPlayTime=0;serverTurnComplete=false;phase='idle';flushResponse();set('listening')}}
function schedule(c,g){if(g!==responseGeneration)return;let n=Math.floor(c.byteLength/2),f=new Float32Array(n),dv=new DataView(c.buffer,c.byteOffset,c.byteLength);for(let i=0;i<n;i++)f[i]=dv.getInt16(i*2,true)/32768;let b=ctx.createBuffer(1,n,RATE);b.copyToChannel(f,0);let s=ctx.createBufferSource();s.buffer=b;s.connect(ctx.destination);let at=Math.max(nextPlayTime||0,ctx.currentTime+MIN);s.start(at);nextPlayTime=at+b.duration;activeSources.add(s);s.onended=()=>{activeSources.delete(s);finishIfDrained(g)}}
function pump(force=false){let g=responseGeneration;if(phase!=='responding')return;if(!playbackStarted){if(!force&&queuedSamples<START)return;playbackStarted=true;set('speaking');nextPlayTime=Math.max(ctx.currentTime+TARGET,nextPlayTime||0)}while(pcmQueue.length){let item=pcmQueue.shift();queuedSamples-=Math.floor(item.data.byteLength/2);if(item.g===g)schedule(item.data,g)}}
function enqueue(c){if(phase!=='responding')return;if(!firstModelAudioAt)firstModelAudioAt=performance.now();pcmQueue.push({g:responseGeneration,data:c});queuedSamples+=Math.floor(c.byteLength/2);pump(false)}
function beginUser(){if(phase==='responding'){resetAudio();send({realtimeInput:{activityStart:{}}});phase='listening'}if(userSpeaking)return;userSpeaking=true;voiceStartedAt=performance.now();inputTranscript='';outputTranscript='';firstModelAudioAt=0;send({realtimeInput:{activityStart:{}}});phase='listening';set('listening')}
function endUser(){if(!userSpeaking)return;userSpeaking=false;lastUserEndAt=performance.now();generation++;responseGeneration=generation;pcmQueue=[];queuedSamples=0;serverTurnComplete=false;playbackStarted=false;nextPlayTime=0;phase='responding';send({realtimeInput:{activityEnd:{}}});set('with you')}
async function mic(){stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false,channelCount:1}});source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(1024,1,1);processor.onaudioprocess=e=>{if(!started||!ws||ws.readyState!==1)return;let f=down(e.inputBuffer.getChannelData(0),ctx.sampleRate),en=0;for(let x of f)en+=x*x;let rms=Math.sqrt(en/Math.max(1,f.length)),now=performance.now();if(rms>=.018){lastVoiceAt=now;if(!userSpeaking)beginUser()}if(userSpeaking){send({realtimeInput:{audio:{data:b64(pcm16(f)),mimeType:'audio/pcm;rate=16000'}}});if(now-lastVoiceAt>END_SILENCE&&now-voiceStartedAt>400)endUser()}};source.connect(processor);processor.connect(ctx.destination)}
async function receive(ev){let d;try{d=JSON.parse(typeof ev.data==='string'?ev.data:await new Blob([ev.data]).text())}catch(e){return}if(d.setupComplete){started=true;phase='idle';set('present');let r=await fetch('/api/m4/prospect-session/'+encodeURIComponent(sessionId),{cache:'no-store'}),h=await r.json(),history=(h.turns||[]);if(history.length){let recap=history.map(t=>(t.speaker==='prospect'?'Person':'M4')+': '+t.text).join('\n');send({clientContent:{turns:[{role:'user',parts:[{text:'We reconnected during the SAME meeting. Temporary private meeting transcript follows. Silently restore context. Continue from the last unfinished point only; do not greet again, restart discovery, or produce a check-in merely because there was silence.\n\n'+recap}]}],turnComplete:true}});phase='responding';generation++;responseGeneration=generation}else{send({clientContent:{turns:[{role:'user',parts:[{text:window.__opening}]}],turnComplete:true}});phase='responding';generation++;responseGeneration=generation}return}let sc=d.serverContent;if(!sc)return;if(sc.inputTranscription&&sc.inputTranscription.text)inputTranscript=merge(inputTranscript,sc.inputTranscription.text);if(sc.outputTranscription&&sc.outputTranscription.text&&phase==='responding')outputTranscript=merge(outputTranscript,sc.outputTranscription.text);if(sc.interrupted){resetAudio();phase=userSpeaking?'listening':'idle';set('listening');return}if(phase!=='responding')return;for(const p of((sc.modelTurn&&sc.modelTurn.parts)||[])){let z=p.inlineData||p.inline_data;if(z&&z.data)enqueue(unb64(z.data))}if(sc.turnComplete){serverTurnComplete=true;pump(true);finishIfDrained(responseGeneration)}}
async function begin(){go.disabled=true;set('connecting');try{ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();let r=await fetch('/api/m4/gemini-token?guest=prospect',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'token');window.__opening=j.opening;await mic();ws=new WebSocket('wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained?access_token='+encodeURIComponent(j.token));ws.binaryType='arraybuffer';ws.onopen=()=>send({setup:{model:'models/'+j.model,generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:j.voice||'Achernar'}}}},realtimeInputConfig:{automaticActivityDetection:{disabled:true}},inputAudioTranscription:{},outputAudioTranscription:{},systemInstruction:{parts:[{text:j.instructions+'\n\nREALTIME TURN CONTRACT: Produce exactly one response to each completed human turn. Never generate a spontaneous check-in, silence filler, are-you-there prompt, or second answer. If the human starts speaking, yield immediately. Do not echo fragments. Prefer a short coherent answer over multiple alternatives. When given the floor to lead, lead: stop ending every statement with a question.'}]}}});ws.onmessage=receive;ws.onerror=()=>set('connection error');ws.onclose=()=>{if(phase==='responding')flushResponse();started=false;phase='idle';set('reconnect by pressing Enter')}}catch(e){set('FAILED: '+e.message)}finally{go.disabled=false}}
go.onclick=begin;</script></body></html>''')
