"""Low-latency Gemini prospect Meeting with durable capture and event observability."""
from fastapi import Request
from fastapi.responses import HTMLResponse
import app as core

@core.app.get('/m4-smooth', response_class=HTMLResponse)
def m4_smooth(request: Request):
    user, redirect = core.login_required_redirect(request)
    if redirect:
        return redirect
    return HTMLResponse(r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>The Meeting</title><style>
html,body{margin:0;height:100%;background:#f3f3ef;color:#1b1d19;font-family:system-ui,sans-serif}.wrap{height:100%;display:grid;place-items:center}.box{text-align:center;width:min(92vw,560px)}h1{font:500 28px Georgia,serif}.state,.rec{font:12px ui-monospace,monospace;color:#74786f;min-height:24px;line-height:1.5}.rec{margin-top:12px}.rec.ok{color:#687a1c}.rec.bad{color:#9b3f36}.go{font:500 20px Georgia,serif;border:1px solid #c8cbc2;border-radius:999px;background:transparent;padding:14px 24px}.dot{width:10px;height:10px;border-radius:50%;background:#687a1c;margin:18px auto}</style></head><body><div class="wrap"><div class="box"><div class="dot"></div><h1>The Meeting</h1><button class="go" id="go">Enter</button><div id="state" class="state">ready</div><div id="rec" class="rec">transcript not started</div></div></div><script>
const go=document.getElementById('go'),state=document.getElementById('state'),rec=document.getElementById('rec');
let sessionId=(crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random());
let ws,ctx,stream,source,processor,started=false,userSpeaking=false,lastVoiceAt=0,voiceStartedAt=0,inputTranscript='',outputTranscript='',lastUserEndAt=0,firstModelAudioAt=0;
let phase='idle',generation=0,responseGeneration=0,pcmQueue=[],queuedSamples=0,playbackStarted=false,nextPlayTime=0,activeSources=new Set(),serverTurnComplete=false,recordingReady=false,turnCount=0,checkpointTimer=null;
let eventSeq=0,eventBuffer=[],eventFlushTimer=null,bargeInPending=false,pendingUserEnd=false,cancelAckTimer=null;
const RATE=24000,START=Math.round(RATE*.24),MIN=.09,TARGET=.16,END_SILENCE=1450,set=s=>state.textContent=s;
function setRec(ok,msg){rec.className='rec '+(ok?'ok':'bad');rec.textContent=msg}
function b64(a){let s='',u=new Uint8Array(a);for(let i=0;i<u.length;i+=8192)s+=String.fromCharCode(...u.subarray(i,i+8192));return btoa(s)}function unb64(s){let x=atob(s),u=new Uint8Array(x.length);for(let i=0;i<x.length;i++)u[i]=x.charCodeAt(i);return u}function send(o){if(ws&&ws.readyState===1)ws.send(JSON.stringify(o))}
function merge(a,b){b=(b||'').trim();if(!b)return a;if(!a)return b;if(b===a)return a;if(b.startsWith(a))return b;if(a.startsWith(b))return a;if(a.endsWith(b))return a;return(a+' '+b).trim()}
function evt(type,detail={},gen=responseGeneration){eventBuffer.push({seq:++eventSeq,type,generation:gen,client_ms:Math.round(performance.now()),detail});if(eventBuffer.length>=20)flushEvents();else{clearTimeout(eventFlushTimer);eventFlushTimer=setTimeout(flushEvents,350)}}
async function flushEvents(){clearTimeout(eventFlushTimer);if(!recordingReady||!eventBuffer.length)return;let batch=eventBuffer.splice(0,eventBuffer.length);try{let r=await fetch('/api/m4/prospect-events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId,events:batch}),cache:'no-store',keepalive:true});if(!r.ok)throw new Error('event write '+r.status)}catch(e){eventBuffer=batch.concat(eventBuffer);setRec(false,'⚠ event recorder interrupted — meeting paused');recordingReady=false;phase='blocked';try{ws&&ws.close()}catch(_){}}}
async function initRecording(){setRec(false,'initializing transcript…');let r=await fetch('/api/m4/prospect-session/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId}),cache:'no-store'});let j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Transcript capture failed to initialize');recordingReady=true;turnCount=Number(j.turn_count||0);setRec(true,'● recording transcript · '+turnCount+' turns safely captured');evt('session_recording_ready',{turn_count:turnCount})}
async function refreshRecording(){if(!recordingReady)return;let r=await fetch('/api/m4/prospect-session/'+encodeURIComponent(sessionId)+'/status',{cache:'no-store'});let j=await r.json();if(!r.ok)throw new Error(j.error||'Recording health check failed');turnCount=Number(j.turn_count||0);setRec(true,'● recording transcript · '+turnCount+' turns safely captured')}
function latencyNow(){return(firstModelAudioAt&&lastUserEndAt)?Math.max(0,Math.round(firstModelAudioAt-lastUserEndAt)):null}
async function checkpoint(inputText=inputTranscript,outputText=outputTranscript,latency=latencyNow()){if(!recordingReady)return false;try{let r=await fetch('/api/m4/prospect-checkpoint',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId,input_text:inputText,output_text:outputText,latency_ms:latency}),cache:'no-store',keepalive:true});let j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'checkpoint failed');evt('checkpoint_committed',{input_chars:inputText.length,output_chars:outputText.length,latency_ms:latency});return true}catch(e){recordingReady=false;setRec(false,'⚠ transcript checkpoint failed — meeting paused');phase='blocked';try{ws&&ws.close()}catch(_){}return false}}
function queueCheckpoint(){if(!recordingReady)return;let i=inputTranscript,o=outputTranscript,l=latencyNow();clearTimeout(checkpointTimer);checkpointTimer=setTimeout(()=>checkpoint(i,o,l),120)}
async function clearCheckpoint(){try{await fetch('/api/m4/prospect-checkpoint/clear',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId}),cache:'no-store',keepalive:true});evt('checkpoint_cleared')}catch(_){}}
async function save(speaker,text,latency_ms=null){text=(text||'').trim();if(!text)return true;if(!recordingReady){setRec(false,'⚠ transcript capture interrupted');return false}try{let r=await fetch('/api/m4/prospect-turn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_id:sessionId,speaker,text,latency_ms}),cache:'no-store',keepalive:true});let j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'write failed');evt('canonical_turn_saved',{speaker,chars:text.length,latency_ms});await refreshRecording();return true}catch(e){recordingReady=false;setRec(false,'⚠ transcript capture interrupted — meeting paused');phase='blocked';try{ws&&ws.close()}catch(_){}return false}}
async function flushResponse(){clearTimeout(checkpointTimer);let a=inputTranscript.trim(),b=outputTranscript.trim(),l=latencyNow();evt('turn_finalize_begin',{input:a,output:b,latency_ms:l});await checkpoint(a,b,l);if(a&&!(await save('prospect',a)))return false;if(b&&!(await save('m4',b,l)))return false;inputTranscript='';outputTranscript='';firstModelAudioAt=0;await clearCheckpoint();evt('turn_finalize_complete');return true}
function down(i,ir,or=16000){if(ir===or)return i;let r=ir/or,n=Math.round(i.length/r),o=new Float32Array(n);for(let x=0;x<n;x++){let a=Math.floor(x*r),b=Math.min(Math.floor((x+1)*r),i.length),s=0;for(let j=a;j<b;j++)s+=i[j];o[x]=s/Math.max(1,b-a)}return o}function pcm16(f){let b=new ArrayBuffer(f.length*2),v=new DataView(b);for(let i=0;i<f.length;i++){let x=Math.max(-1,Math.min(1,f[i]));v.setInt16(i*2,x<0?x*32768:x*32767,true)}return b}
function resetAudio(reason='reset'){generation++;evt('generation_invalidated',{reason,new_generation:generation},generation);for(const s of activeSources){try{s.stop()}catch(_){}}activeSources.clear();pcmQueue=[];queuedSamples=0;playbackStarted=false;nextPlayTime=0;serverTurnComplete=false;responseGeneration=generation}
async function finishIfDrained(g){if(g!==responseGeneration)return;if(serverTurnComplete&&!activeSources.size&&!pcmQueue.length){evt('playback_drained',{},g);playbackStarted=false;nextPlayTime=0;serverTurnComplete=false;phase='saving';set('saving');if(await flushResponse()){phase='idle';set('listening')}}}
function schedule(c,g){if(g!==responseGeneration){evt('stale_audio_discarded',{stage:'schedule'},g);return}let n=Math.floor(c.byteLength/2),f=new Float32Array(n),dv=new DataView(c.buffer,c.byteOffset,c.byteLength);for(let i=0;i<n;i++)f[i]=dv.getInt16(i*2,true)/32768;let b=ctx.createBuffer(1,n,RATE);b.copyToChannel(f,0);let s=ctx.createBufferSource();s.buffer=b;s.connect(ctx.destination);let at=Math.max(nextPlayTime||0,ctx.currentTime+MIN);s.start(at);if(!activeSources.size)evt('playback_started',{scheduled_at:at},g);nextPlayTime=at+b.duration;activeSources.add(s);s.onended=()=>{activeSources.delete(s);if(!activeSources.size)evt('playback_chunk_queue_empty',{},g);finishIfDrained(g)}}
function pump(force=false){let g=responseGeneration;if(phase!=='responding')return;if(!playbackStarted){if(!force&&queuedSamples<START)return;playbackStarted=true;set('speaking');nextPlayTime=Math.max(ctx.currentTime+TARGET,nextPlayTime||0)}while(pcmQueue.length){let item=pcmQueue.shift();queuedSamples-=Math.floor(item.data.byteLength/2);if(item.g===g)schedule(item.data,g);else evt('stale_audio_discarded',{stage:'pump',item_generation:item.g},g)}}
function enqueue(c){if(phase!=='responding'){evt('model_audio_ignored',{phase});return}if(!firstModelAudioAt){firstModelAudioAt=performance.now();evt('first_model_audio',{latency_ms:latencyNow()})}pcmQueue.push({g:responseGeneration,data:c});queuedSamples+=Math.floor(c.byteLength/2);pump(false)}
function finalizeUserTurn(){clearTimeout(cancelAckTimer);bargeInPending=false;pendingUserEnd=false;lastUserEndAt=performance.now();generation++;responseGeneration=generation;pcmQueue=[];queuedSamples=0;serverTurnComplete=false;playbackStarted=false;nextPlayTime=0;phase='responding';evt('generation_started',{input_so_far:inputTranscript},responseGeneration);send({realtimeInput:{activityEnd:{}}});queueCheckpoint();set('with you')}
function beginUser(){if(!recordingReady||phase==='blocked'||phase==='saving')return;if(userSpeaking)return;let interruptedModel=(phase==='responding'||playbackStarted||activeSources.size>0);if(interruptedModel){evt('human_barge_in',{phase,active_sources:activeSources.size});queueCheckpoint();bargeInPending=true;resetAudio('human_barge_in')}userSpeaking=true;voiceStartedAt=performance.now();lastVoiceAt=voiceStartedAt;send({realtimeInput:{activityStart:{}}});phase='listening';evt('speech_start',{barge_in:interruptedModel});set('listening')}
function endUser(){if(!userSpeaking)return;userSpeaking=false;evt('speech_end',{duration_ms:Math.round(performance.now()-voiceStartedAt),assembled_input:inputTranscript});if(bargeInPending){pendingUserEnd=true;phase='awaiting_cancel';evt('waiting_for_cancel_ack');clearTimeout(cancelAckTimer);cancelAckTimer=setTimeout(()=>{evt('cancel_ack_timeout');finalizeUserTurn()},650);set('with you');return}finalizeUserTurn()}
async function mic(){stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:false,channelCount:1}});evt('microphone_ready',{tracks:stream.getAudioTracks().map(t=>({enabled:t.enabled,muted:t.muted,readyState:t.readyState}))});source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(1024,1,1);processor.onaudioprocess=e=>{if(!started||!recordingReady||!ws||ws.readyState!==1)return;let f=down(e.inputBuffer.getChannelData(0),ctx.sampleRate),en=0;for(let x of f)en+=x*x;let rms=Math.sqrt(en/Math.max(1,f.length)),now=performance.now();if(rms>=.018){lastVoiceAt=now;if(!userSpeaking)beginUser()}if(userSpeaking){send({realtimeInput:{audio:{data:b64(pcm16(f)),mimeType:'audio/pcm;rate=16000'}}});if(now-lastVoiceAt>END_SILENCE&&now-voiceStartedAt>400)endUser()}};source.connect(processor);processor.connect(ctx.destination)}
async function receive(ev){let d;try{d=JSON.parse(typeof ev.data==='string'?ev.data:await new Blob([ev.data]).text())}catch(e){evt('server_message_parse_error',{message:String(e)});return}if(d.setupComplete){started=true;phase='idle';evt('gemini_setup_complete');set('present');let r=await fetch('/api/m4/prospect-session/'+encodeURIComponent(sessionId),{cache:'no-store'}),h=await r.json(),history=(h.turns||[]);if(history.length){let recap=history.map(t=>(t.speaker==='prospect'?'Person':'M4')+': '+t.text).join('\n');evt('reconnect_context_restored',{turn_count:history.length,last_turn:history[history.length-1]});send({clientContent:{turns:[{role:'user',parts:[{text:'We reconnected during the SAME meeting. The temporary private transcript follows. Restore FACT, CONVERSATIONAL, and BEHAVIORAL state silently. Continue from the last unresolved intellectual point. Do not greet, say you lost the thread, ask for a reminder, or restart discovery.\n\n'+recap}]}],turnComplete:true}})}else{evt('new_meeting_opening');send({clientContent:{turns:[{role:'user',parts:[{text:window.__opening}]}],turnComplete:true}})}phase='responding';generation++;responseGeneration=generation;evt('generation_started',{kind:history.length?'reconnect':'opening'},responseGeneration);return}let sc=d.serverContent;if(!sc)return;if(sc.inputTranscription&&sc.inputTranscription.text){let raw=sc.inputTranscription.text;evt('raw_input_transcription',{text:raw});inputTranscript=merge(inputTranscript,raw);evt('assembled_input_transcription',{text:inputTranscript});queueCheckpoint()}if(sc.outputTranscription&&sc.outputTranscription.text){let raw=sc.outputTranscription.text;evt('raw_output_transcription',{text:raw});if(phase==='responding'){outputTranscript=merge(outputTranscript,raw);evt('assembled_output_transcription',{text:outputTranscript});queueCheckpoint()}else evt('output_transcription_ignored',{phase,text:raw})}if(sc.interrupted){evt('gemini_interrupted_ack',{pendingUserEnd,phase});resetAudio('gemini_interrupted_ack');bargeInPending=false;if(pendingUserEnd)finalizeUserTurn();else{phase=userSpeaking?'listening':'idle';set('listening')}return}if(phase!=='responding'){if((sc.modelTurn&&sc.modelTurn.parts||[]).length)evt('model_turn_ignored',{phase});return}for(const p of((sc.modelTurn&&sc.modelTurn.parts)||[])){let z=p.inlineData||p.inline_data;if(z&&z.data)enqueue(unb64(z.data))}if(sc.turnComplete){evt('server_turn_complete',{output:outputTranscript});serverTurnComplete=true;queueCheckpoint();pump(true);finishIfDrained(responseGeneration)}}
async function begin(){go.disabled=true;set('initializing');try{await initRecording();ctx=ctx||new(window.AudioContext||window.webkitAudioContext)();await ctx.resume();evt('audio_context_ready',{sample_rate:ctx.sampleRate,state:ctx.state});let r=await fetch('/api/m4/gemini-token?guest=prospect',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'token');evt('gemini_token_ready',{model:j.model,voice:j.voice});window.__opening=j.opening;await mic();ws=new WebSocket('wss://generativelanguage.googleapis.com/ws/google.ai.generativelanguage.v1beta.GenerativeService.BidiGenerateContentConstrained?access_token='+encodeURIComponent(j.token));ws.binaryType='arraybuffer';ws.onopen=()=>{evt('websocket_open');send({setup:{model:'models/'+j.model,generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:j.voice||'Achernar'}}}},realtimeInputConfig:{automaticActivityDetection:{disabled:true}},inputAudioTranscription:{},outputAudioTranscription:{},systemInstruction:{parts:[{text:j.instructions+'\n\nREALTIME TURN CONTRACT: Produce exactly one response to each completed human turn. Never generate spontaneous silence filler or a second answer. If the human starts speaking, yield immediately. Do not echo fragments. When given the floor to lead, lead. Never claim access to shop-specific evidence not present in current context.'}]}}})};ws.onmessage=receive;ws.onerror=e=>{evt('websocket_error',{online:navigator.onLine});set('connection error')};ws.onclose=e=>{evt('websocket_close',{code:e.code,reason:e.reason,was_clean:e.wasClean,online:navigator.onLine});queueCheckpoint();started=false;if(recordingReady)set('reconnect by pressing Enter');flushEvents()}}catch(e){evt('meeting_start_failed',{message:e.message});await flushEvents();recordingReady=false;setRec(false,'⚠ transcript unavailable — meeting did not start');set('FAILED: '+e.message)}finally{go.disabled=false}}
go.onclick=begin;
window.addEventListener('online',()=>evt('browser_online'));
window.addEventListener('offline',()=>evt('browser_offline'));
window.addEventListener('pagehide',()=>{if(recordingReady){evt('pagehide',{phase,online:navigator.onLine});let events=eventBuffer.splice(0,eventBuffer.length);if(events.length)navigator.sendBeacon('/api/m4/prospect-events',new Blob([JSON.stringify({session_id:sessionId,events})],{type:'application/json'}));navigator.sendBeacon('/api/m4/prospect-checkpoint',new Blob([JSON.stringify({session_id:sessionId,input_text:inputTranscript,output_text:outputTranscript,latency_ms:latencyNow()})],{type:'application/json'}));navigator.sendBeacon('/api/m4/prospect-session/finish',new Blob([JSON.stringify({session_id:sessionId})],{type:'application/json'}))}});
</script></body></html>''')
