import SwiftUI
import EventKit
import LocalAuthentication
import Security
import BackgroundTasks
import UIKit

final class BackgroundSyncCoordinator {
    static let shared=BackgroundSyncCoordinator();weak var model:EmptyChairModel?;let identifier="com.tryemptychair.calendar-sync"
    func register(){BGTaskScheduler.shared.register(forTaskWithIdentifier:identifier,using:nil){task in guard let refresh=task as? BGAppRefreshTask else{task.setTaskCompleted(success:false);return};self.schedule();let work=Task{@MainActor in await self.model?.sync();refresh.setTaskCompleted(success:true)};refresh.expirationHandler={work.cancel()}}}
    func schedule(){let request=BGAppRefreshTaskRequest(identifier:identifier);request.earliestBeginDate=Date(timeIntervalSinceNow:15*60);try? BGTaskScheduler.shared.submit(request)}
}
final class AppDelegate:NSObject,UIApplicationDelegate {func application(_ application:UIApplication,didFinishLaunchingWithOptions launchOptions:[UIApplication.LaunchOptionsKey:Any]?=nil)->Bool{BackgroundSyncCoordinator.shared.register();BackgroundSyncCoordinator.shared.schedule();return true};func applicationDidEnterBackground(_ application:UIApplication){BackgroundSyncCoordinator.shared.schedule()}}
@main struct EmptyChairApp:App{@UIApplicationDelegateAdaptor(AppDelegate.self)var appDelegate;@StateObject private var model:EmptyChairModel;init(){let m=EmptyChairModel();_model=StateObject(wrappedValue:m);BackgroundSyncCoordinator.shared.model=m};var body:some Scene{WindowGroup{RootView().environmentObject(model)}}}

struct NativeEvent:Codable{let id:String;let title:String;let start_at:String;let end_at:String}
struct NativeCommand:Codable{let id:String;let kind:String;let payload:CommandPayload}
struct CommandPayload:Codable{let title:String;let start_at:String;let end_at:String;let notes:String?}
struct SyncReply:Codable{let ok:Bool;let commands:[NativeCommand]}
struct SyncPayload:Codable{let calendar_id:String;let events:[NativeEvent]}
struct AuthStartReply:Codable{let challenge_id:String;let last4:String}
struct AuthVerifyReply:Codable{let device_token:String;let artist_id:String;let artist_name:String}
struct HunterTarget:Codable,Equatable{let account_id:String;let username:String;let name:String;let market:String;let source:String;let profile_url:String}
struct HunterStats:Codable{let remaining:Int;let handled_today:Int;let skipped_today:Int}
struct HunterReply:Codable{let ok:Bool;let target:HunterTarget?;let stats:HunterStats}
struct Keychain{static let service="com.tryemptychair.EmptyChair";static func set(_ value:String,key:String){let data=Data(value.utf8);SecItemDelete([kSecClass:kSecClassGenericPassword,kSecAttrService:service,kSecAttrAccount:key] as CFDictionary);SecItemAdd([kSecClass:kSecClassGenericPassword,kSecAttrService:service,kSecAttrAccount:key,kSecValueData:data,kSecAttrAccessible:kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly] as CFDictionary,nil)};static func get(_ key:String)->String?{var item:CFTypeRef?;let status=SecItemCopyMatching([kSecClass:kSecClassGenericPassword,kSecAttrService:service,kSecAttrAccount:key,kSecReturnData:true,kSecMatchLimit:kSecMatchLimitOne] as CFDictionary,&item);guard status==errSecSuccess,let data=item as? Data else{return nil};return String(data:data,encoding:.utf8)}}

@MainActor final class EmptyChairModel:ObservableObject{
    @Published var unlocked=false;@Published var linked=Keychain.get("deviceToken") != nil;@Published var phone="";@Published var code="";@Published var challengeID:String?;@Published var authMessage="";@Published var calendarAuthorized=false;@Published var calendars:[EKCalendar]=[];@Published var selectedCalendarID=UserDefaults.standard.string(forKey:"tattooCalendarID");@Published var status="LOCKED";@Published var hunterTarget:HunterTarget?;@Published var hunterStats:HunterStats?;@Published var hunterStatus="READY"
    let store=EKEventStore();let api=URL(string:"https://app.tryemptychair.com")!;private let iso=ISO8601DateFormatter()
    init(){NotificationCenter.default.addObserver(forName:.EKEventStoreChanged,object:nil,queue:.main){[weak self]_ in Task{@MainActor in await self?.sync()}}}
    func unlock()async{let context=LAContext();if context.canEvaluatePolicy(.deviceOwnerAuthentication,error:nil){do{unlocked=try await context.evaluatePolicy(.deviceOwnerAuthentication,localizedReason:"Open Empty Chair")}catch{status="LOCKED";return}}else{unlocked=true};await loadCalendarState()}
    func startPhoneLink()async{guard let body=try? JSONSerialization.data(withJSONObject:["phone":phone,"platform":"ios"])else{return};var r=URLRequest(url:api.appending(path:"native/auth/start"));r.httpMethod="POST";r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.httpBody=body;do{let(data,response)=try await URLSession.shared.data(for:r);guard(response as? HTTPURLResponse)?.statusCode==200 else{authMessage="CHECK THAT MOBILE NUMBER";return};let reply=try JSONDecoder().decode(AuthStartReply.self,from:data);challengeID=reply.challenge_id;authMessage="CODE SENT TO ***\(reply.last4)"}catch{authMessage="CHECK CONNECTION"}}
    func verifyPhoneLink()async{guard let challengeID else{return};let payload:[String:String]=["challenge_id":challengeID,"code":code,"calendar_id":selectedCalendarID ?? "","platform":"ios"];guard let body=try? JSONSerialization.data(withJSONObject:payload)else{return};var r=URLRequest(url:api.appending(path:"native/auth/verify"));r.httpMethod="POST";r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.httpBody=body;do{let(data,response)=try await URLSession.shared.data(for:r);guard(response as? HTTPURLResponse)?.statusCode==200 else{authMessage="THAT CODE DIDN'T WORK";return};let reply=try JSONDecoder().decode(AuthVerifyReply.self,from:data);Keychain.set(reply.device_token,key:"deviceToken");linked=true;authMessage="LINKED [✓]";await loadCalendarState()}catch{authMessage="CHECK CONNECTION"}}
    func loadCalendarState()async{guard linked else{return};let auth=EKEventStore.authorizationStatus(for:.event);if #available(iOS 17.0,*){calendarAuthorized=auth == .fullAccess}else{calendarAuthorized=auth == .authorized};if calendarAuthorized{calendars=store.calendars(for:.event).filter{$0.allowsContentModifications};status=selectedCalendarID == nil ? "CHOOSE CALENDAR":"ARMED";await sync()}}
    func connectAppleCalendar()async{do{if #available(iOS 17.0,*){calendarAuthorized=try await store.requestFullAccessToEvents()}else{calendarAuthorized=try await store.requestAccess(to:.event)};if calendarAuthorized{calendars=store.calendars(for:.event).filter{$0.allowsContentModifications};status="CHOOSE CALENDAR"}}catch{status="CHECK CALENDAR"}}
    func choose(_ calendar:EKCalendar){selectedCalendarID=calendar.calendarIdentifier;UserDefaults.standard.set(calendar.calendarIdentifier,forKey:"tattooCalendarID");status="ARMED";Task{await sync()}}
    func sync()async{guard linked,calendarAuthorized,let calendarID=selectedCalendarID,let calendar=store.calendar(withIdentifier:calendarID),let token=Keychain.get("deviceToken")else{return};let predicate=store.predicateForEvents(withStart:Date().addingTimeInterval(-86400),end:Date().addingTimeInterval(86400*180),calendars:[calendar]);let events=store.events(matching:predicate).map{NativeEvent(id:$0.eventIdentifier ?? $0.calendarItemIdentifier,title:$0.title ?? "Tattoo",start_at:iso.string(from:$0.startDate),end_at:iso.string(from:$0.endDate))};var r=URLRequest(url:api.appending(path:"native/calendar/sync"));r.httpMethod="POST";r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization");r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.httpBody=try? JSONEncoder().encode(SyncPayload(calendar_id:calendarID,events:events));guard let(data,response)=try? await URLSession.shared.data(for:r),(response as? HTTPURLResponse)?.statusCode==200,let reply=try? JSONDecoder().decode(SyncReply.self,from:data)else{status="CHECK CONNECTION";return};for command in reply.commands where command.kind=="upsert_event"{await apply(command,calendar:calendar,token:token)};status="ARMED";BackgroundSyncCoordinator.shared.schedule()}
    private func ack(_ commandID:String,token:String)async{var r=URLRequest(url:api.appending(path:"native/calendar/ack/\(commandID)"));r.httpMethod="POST";r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization");_=try? await URLSession.shared.data(for:r)}
    private func apply(_ command:NativeCommand,calendar:EKCalendar,token:String)async{guard let start=iso.date(from:command.payload.start_at),let end=iso.date(from:command.payload.end_at)else{return};let marker=URL(string:"emptychair://command/\(command.id)")!;let existing=store.events(matching:store.predicateForEvents(withStart:start.addingTimeInterval(-60),end:end.addingTimeInterval(60),calendars:[calendar])).contains{$0.url==marker};if existing{await ack(command.id,token:token);return};let event=EKEvent(eventStore:store);event.calendar=calendar;event.title=command.payload.title;event.startDate=start;event.endDate=end;event.notes=command.payload.notes;event.url=marker;do{try store.save(event,span:.thisEvent,commit:true)}catch{status="CHECK CALENDAR";return};await ack(command.id,token:token)}
    func loadHunter()async{guard let token=Keychain.get("deviceToken")else{return};hunterStatus="LOADING";var r=URLRequest(url:api.appending(path:"native/hunter/next"));r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization");do{let(data,response)=try await URLSession.shared.data(for:r);guard(response as? HTTPURLResponse)?.statusCode==200 else{hunterStatus="UNAVAILABLE";return};let reply=try JSONDecoder().decode(HunterReply.self,from:data);hunterTarget=reply.target;hunterStats=reply.stats;hunterStatus=reply.target == nil ? "QUEUE CLEAR":"READY"}catch{hunterStatus="CHECK CONNECTION"}}
    func hunterDecision(_ decision:String,openInstagram:Bool)async{guard let target=hunterTarget,let token=Keychain.get("deviceToken")else{return};hunterStatus="SAVING";let payload=["decision":decision];guard let body=try? JSONSerialization.data(withJSONObject:payload)else{return};var r=URLRequest(url:api.appending(path:"native/hunter/\(target.account_id)/decision"));r.httpMethod="POST";r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization");r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.httpBody=body;do{let(_,response)=try await URLSession.shared.data(for:r);guard(response as? HTTPURLResponse)?.statusCode==200 else{hunterStatus="TRY AGAIN";return};let username=target.username;await loadHunter();if openInstagram{openInstagramProfile(username)}}catch{hunterStatus="CHECK CONNECTION"}}
    private func openInstagramProfile(_ username:String){let encoded=username.addingPercentEncoding(withAllowedCharacters:.urlPathAllowed) ?? username;let appURL=URL(string:"instagram://user?username=\(encoded)")!;UIApplication.shared.open(appURL,options:[:]){opened in if !opened,let web=URL(string:"https://www.instagram.com/_u/\(encoded)/"){UIApplication.shared.open(web)}}}
}

struct RootView:View{@EnvironmentObject var model:EmptyChairModel;var body:some View{NavigationStack{ZStack{Color(red:11/255,green:9/255,blue:5/255).ignoresSafeArea();VStack(alignment:.leading,spacing:24){HStack{Text("EMPTY CHAIR");Spacer();Text("2.0")}.font(.system(.headline,design:.monospaced));Divider();if !model.unlocked{Text("EMPTY CHAIR // LOCKED").font(.system(.largeTitle,design:.monospaced));Button("UNLOCK"){Task{await model.unlock()}}.buttonStyle(TerminalButton())}else if !model.linked{Text("LINK THIS IPHONE").font(.system(.title,design:.monospaced));if model.challengeID==nil{TextField("MOBILE",text:$model.phone).keyboardType(.phonePad).padding().overlay(Rectangle().stroke());Button("TEXT ME A CODE"){Task{await model.startPhoneLink()}}.buttonStyle(TerminalButton())}else{Text(model.authMessage);TextField("6-DIGIT CODE",text:$model.code).keyboardType(.numberPad).padding().overlay(Rectangle().stroke());Button("VERIFY THIS IPHONE"){Task{await model.verifyPhoneLink()}}.buttonStyle(TerminalButton())}}else if !model.calendarAuthorized{Text("WHERE DO YOUR APPOINTMENTS LIVE?").font(.system(.title,design:.monospaced));Button("[ A ] APPLE CALENDAR"){Task{await model.connectAppleCalendar()}}.buttonStyle(TerminalButton())}else if model.selectedCalendarID==nil{Text("WHICH ONE HOLDS TATTOOS?").font(.system(.title,design:.monospaced));ForEach(model.calendars,id:\.calendarIdentifier){cal in Button(cal.title.uppercased()){model.choose(cal)}.buttonStyle(TerminalButton())}}else{Spacer();Text(model.status=="ARMED" ? "ARMED. ✓":"EMPTY CHAIR // \(model.status)").font(.system(size:40,weight:.medium,design:.monospaced));Text(model.status=="ARMED" ? "calendar................[✓]":"Open Empty Chair again when your connection is restored.").font(.system(.body,design:.monospaced));NavigationLink(destination:HunterView().environmentObject(model)){Text("OPEN HUNTER").frame(maxWidth:.infinity).padding().overlay(Rectangle().stroke())}.buttonStyle(.plain);Spacer()};Spacer()}.padding(24).foregroundStyle(Color(red:1,green:176/255,blue:0))}}.task{await model.unlock()}}}

struct HunterView:View{@EnvironmentObject var model:EmptyChairModel;@State private var offset:CGSize=.zero;@State private var swiping=false;let amber=Color(red:1,green:176/255,blue:0);var body:some View{ZStack{Color(red:11/255,green:9/255,blue:5/255).ignoresSafeArea();VStack(spacing:18){HStack{Text("HUNTER").font(.system(.title2,design:.monospaced));Spacer();if let stats=model.hunterStats{Text("\(stats.remaining) LEFT").font(.system(.caption,design:.monospaced))}};if let target=model.hunterTarget{Spacer();VStack(spacing:14){Text(target.name.isEmpty ? "NEXT ARTIST":target.name.uppercased()).font(.system(.headline,design:.monospaced));Text("@\(target.username)").font(.system(size:34,weight:.bold,design:.monospaced));let context=[target.market,target.source].filter{!$0.isEmpty}.joined(separator:" · ");if !context.isEmpty{Text(context).multilineTextAlignment(.center).font(.system(.footnote,design:.monospaced))};Text(offset.width>70 ? "FOLLOW →":offset.width < -70 ? "← SKIP":"SWIPE RIGHT TO FOLLOW\nSWIPE LEFT TO SKIP").multilineTextAlignment(.center).font(.system(.body,design:.monospaced)).padding(.top,20)}.padding(28).frame(maxWidth:.infinity,minHeight:360).overlay(RoundedRectangle(cornerRadius:20).stroke(amber,lineWidth:2)).rotationEffect(.degrees(Double(offset.width/24))).offset(x:offset.width,y:offset.height*0.12).gesture(DragGesture().onChanged{value in if !swiping{offset=value.translation}}.onEnded{value in guard !swiping else{return};if value.translation.width>110{commit("HANDLED",open:true)}else if value.translation.width < -110{commit("SKIPPED",open:false)}else{withAnimation(.spring()){offset=.zero}}});HStack{Button("← SKIP"){commit("SKIPPED",open:false)}.buttonStyle(TerminalButton());Button("FOLLOW →"){commit("HANDLED",open:true)}.buttonStyle(TerminalButton())};Spacer();if let stats=model.hunterStats{Text("TODAY // \(stats.handled_today) FOLLOW INTENTS · \(stats.skipped_today) SKIPPED").font(.system(.caption,design:.monospaced))}}else{Spacer();Text(model.hunterStatus=="QUEUE CLEAR" ? "QUEUE CLEAR ✓":model.hunterStatus).font(.system(.title2,design:.monospaced));Spacer()}}.padding(24).foregroundStyle(amber)}.task{await model.loadHunter()}}
    private func commit(_ decision:String,open:Bool){guard !swiping else{return};swiping=true;withAnimation(.easeIn(duration:0.18)){offset=CGSize(width:decision=="HANDLED" ? 520:-520,height:0)};Task{await model.hunterDecision(decision,openInstagram:open);offset=.zero;swiping=false}}
}

struct TerminalButton:ButtonStyle{func makeBody(configuration:Configuration)->some View{configuration.label.font(.system(.headline,design:.monospaced)).frame(maxWidth:.infinity).padding().overlay(Rectangle().stroke()).opacity(configuration.isPressed ? 0.6:1)}}
